[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:vite"
  targetPort = 5173

[build]
  base = "galleria-slideshow-site"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"